### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Jaydenm5** [LogsC/EEP153-Project4-Spring2023#2]
When running the code, everything ran smoothly and there were no errors. I was able to replicate the same graph and they look really good. The only recommendations I have for improving elegance and clarity would be to add brief titles to the graph plots and maybe more specifically indicate which deliverable is associated with which code visualization. Other than that, great job!

**Comment by LogsC** [comment]
Thank you for letting us know! We will work on your suggestions!
